"""The built-in scene presets: art direction only.

Ten scenes, and not one camera figure among them. Every number a plate is composed against — the
horizon, the foot anchor, the keep-clear band, the field of view — is read from the runtime's
camera contract at generation time and compiled into the prompt by `plate_package`. That split is
the point of this file: adding a scene is writing a paragraph, and changing the camera is
re-exporting a contract. Neither touches the other.

The temptation it exists to resist is to paste "feet at 89.7%" into each entry so the prompts read
completely. Ten copies of a measurement is ten places to miss when the camera moves, and the
failure is silent — the art still generates, it just no longer fits.

## What a `subject` is

The artistic half, written as if briefing a photographer who will never see the avatar: what the
place is, what time it is, where the light comes from, what is in the foreground. It must not
describe the character, the safe zone or the geometry; `build_prompt` appends all of that.

Two rules are in every subject rather than in the compiler, because they are art direction rather
than geometry: **an original place**, not a recognisable real or fictional one, and **a usable
standing surface** in the foreground. A scene that is beautiful and has nowhere to stand is the
characteristic failure of this whole route — scenic wallpaper with the character pasted onto it.

## `lighting`

An approximation the runtime can actually reproduce with a key light, a hemisphere fill and an
exposure. It is not a description of the picture; it is the three-value summary a Three.js scene
can be set up from, so the avatar is lit roughly the way the plate behind her is.
"""

from __future__ import annotations

from typing import Any

#: Bumped when the compiler's technical paragraph changes shape. Recorded in provenance, so a
#: resumable batch can tell "already generated" from "generated by an older recipe".
PROMPT_VERSION = 1

_ORIGINAL = "An original place, not a real or fictional location."
_NO_PEOPLE = "Empty environment art with no people of any kind."


def _scene(
    scene_id: str,
    name: str,
    category: str,
    tags: list[str],
    subject: str,
    lighting: dict[str, Any],
    fallback: str,
    description: str = "",
) -> dict[str, Any]:
    return {
        "id": scene_id,
        "version": "1.0.0",
        "name": name,
        "description": description,
        "category": category,
        "tags": tags,
        "fallbackColor": fallback,
        "lighting": lighting,
        "subject": f"{subject} {_ORIGINAL} {_NO_PEOPLE}",
    }


PRESETS: dict[str, dict[str, Any]] = {
    "ocean-sunrise": _scene(
        "ocean-sunrise",
        "Ocean — Sunrise",
        "relax",
        ["water", "coast", "sunrise", "calm", "outdoor", "bright"],
        (
            "A peaceful coastal ocean viewpoint at sunrise. Calm water stretching to subtle distant "
            "landforms. A soft golden sun low in the sky, well off to one side. The foreground is a "
            "readable natural stone and weathered timber platform at the water's edge, flat and "
            "continuous. Fresh early-morning air with gentle haze over the water. Warm light arriving "
            "obliquely from the side, with no glare in the middle of the frame."
        ),
        {"preset": "warm-sunrise-side", "exposure": 1.05, "keyDirection": [-0.8, 0.35, 0.5], "temperatureK": 3200},
        "#20344a",
        "Low sun over calm water, from a timber and stone platform.",
    ),
    "ocean-moonlight": _scene(
        "ocean-moonlight",
        "Ocean — Moonlight",
        "sleep",
        ["water", "coast", "night", "moonlight", "calm", "outdoor"],
        (
            "A quiet open ocean at night under a cool moonlit sky with restrained stars. Calm dark blue "
            "water, a distant low coastline. The moon sits well off to one side, its reflection running "
            "away from the middle of the frame. The foreground is a flat stone and timber standing "
            "surface, continuous and readable in the moonlight."
        ),
        {"preset": "cool-moonlight-side", "exposure": 1.0, "keyDirection": [-1, 0.9, 0.4], "temperatureK": 7200},
        "#0a1626",
        "Moonlight on open water, from a low stone deck.",
    ),
    "mountain-lake-day": _scene(
        "mountain-lake-day",
        "Mountain Lake — Day",
        "nature",
        ["water", "mountain", "lake", "nature", "day", "calm"],
        (
            "A clear, peaceful mountain lake in daylight. Calm reflective water, layered ranges receding "
            "into clean atmosphere. The foreground is a stable lakeshore deck of flat fitted stone and "
            "timber boards — even underfoot, with no loose boulders. Strong separation between "
            "foreground, water and distant peaks."
        ),
        {"preset": "neutral-daylight", "exposure": 1.0, "keyDirection": [-0.6, 0.8, 0.4], "temperatureK": 5800},
        "#33506a",
        "An alpine lake seen from a flat shoreline deck.",
    ),
    "mountain-lake-night": _scene(
        "mountain-lake-night",
        "Mountain Lake — Night",
        "nature",
        ["water", "mountain", "lake", "nature", "night", "calm"],
        (
            "A mountain lake under a moonlit night sky with restrained stars. Distant mountain "
            "silhouettes, subtle reflections on still water. The foreground is a flat, safe timber and "
            "stone viewpoint, lit well enough to read clearly. Cool directional light from one side; "
            "the middle of the frame stays legible rather than falling into darkness."
        ),
        {"preset": "cool-moonlight-side", "exposure": 1.05, "keyDirection": [-0.9, 0.8, 0.35], "temperatureK": 7000},
        "#101d2e",
        "Still water and mountain silhouettes by moonlight.",
    ),
    "meditation-garden-day": _scene(
        "meditation-garden-day",
        "Meditation Garden — Day",
        "meditation",
        ["meditation", "garden", "nature", "day", "calm", "restful"],
        (
            "A tranquil contemplative garden in soft daylight. Raked ground, natural stone, moss and "
            "restrained planting. A small water element sits well to one side. The middle of the "
            "composition is clean, flat, swept stone. Planting and low timber structures frame the far "
            "left and far right only. Balanced and minimal."
        ),
        {"preset": "soft-daylight", "exposure": 1.0, "keyDirection": [-0.5, 0.85, 0.3], "temperatureK": 5600},
        "#4a5140",
        "Swept stone and restrained planting in daylight.",
    ),
    "meditation-garden-night": _scene(
        "meditation-garden-night",
        "Meditation Garden — Night",
        "meditation",
        ["meditation", "garden", "nature", "night", "calm", "restful"],
        (
            "A contemplative garden at night under cool moonlight. Flat swept stone through the middle "
            "of the composition. Very restrained warm lantern light at the far left and right edges "
            "only, none of it near the middle. Soft atmospheric depth between near stone, planting and "
            "the dark beyond."
        ),
        {"preset": "cool-night-warm-edge", "exposure": 1.1, "keyDirection": [-0.8, 0.85, 0.3], "temperatureK": 6800},
        "#1b2026",
        "A garden by moonlight, with lanterns kept to the edges.",
    ),
    "coastal-terrace-day": _scene(
        "coastal-terrace-day",
        "Coastal Terrace — Day",
        "chill",
        ["water", "coast", "terrace", "outdoor", "day", "calm"],
        (
            "An elegant Mediterranean-inspired coastal terrace in daylight. Pale natural stone paving, "
            "simple original architecture and low walls at the edges, sea beyond and a distant coast. "
            "Sparse planting at the far sides. The central view over the water is open. Bright and "
            "clear without blown highlights."
        ),
        {"preset": "neutral-daylight", "exposure": 0.95, "keyDirection": [-0.7, 0.8, 0.35], "temperatureK": 5800},
        "#2c5a74",
        "Pale stone, low walls and open sea in daylight.",
    ),
    "coastal-terrace-twilight": _scene(
        "coastal-terrace-twilight",
        "Coastal Terrace — Twilight",
        "chill",
        ["water", "coast", "terrace", "twilight", "evening", "calm"],
        (
            "An elegant Mediterranean-inspired coastal terrace during blue-hour twilight. Deep blue sea, "
            "the last warm light low near the horizon, the sky already deepening overhead. Pale stone "
            "paving in the foreground, subtle warm edge lighting on low walls at the sides. Nothing "
            "prominent stands in the middle of the composition."
        ),
        {"preset": "twilight-warm-horizon", "exposure": 1.05, "keyDirection": [-0.6, 0.4, 0.7], "temperatureK": 4200},
        "#1d2f46",
        "Blue hour over the sea from a stone terrace.",
    ),
    "open-sky-day": _scene(
        "open-sky-day",
        "Open Sky — Day",
        "relax",
        ["sky", "open", "day", "peaceful", "minimal"],
        (
            "A minimal elevated viewpoint under a large, beautiful daytime sky with soft cumulus. The "
            "landscape below is very distant and low in the frame. The foreground is a simple flat "
            "natural stone platform with a clearly readable edge — spacious and uncluttered, but "
            "unmistakably a surface to stand on rather than open air."
        ),
        {"preset": "neutral-daylight", "exposure": 1.0, "keyDirection": [-0.5, 0.9, 0.3], "temperatureK": 6000},
        "#6f97bd",
        "A high, simple stone platform under a wide sky.",
    ),
    "open-sky-starlight": _scene(
        "open-sky-starlight",
        "Open Sky — Starlight",
        "sleep",
        ["sky", "open", "stars", "night", "peaceful", "minimal"],
        (
            "A minimal elevated viewpoint at night under a rich but realistic star field, the Milky Way "
            "present only as a subtle band. A very distant landscape silhouette low in the frame. The "
            "foreground is a simple flat stone platform, lit just enough by starlight and a low moon "
            "off to one side to read as solid ground. Quiet and spacious."
        ),
        {"preset": "cool-starlight", "exposure": 1.15, "keyDirection": [-0.85, 0.8, 0.35], "temperatureK": 7600},
        "#0b1020",
        "A flat stone platform under stars.",
    ),
}

#: The proof-of-concept artefact, kept deliberately.
#:
#: It is a *different art direction* from `coastal-terrace-twilight` — a night terrace under a full
#: moon rather than a blue-hour one — so it is not that scene under another name, and replacing one
#: with the other would quietly lose the only plate whose fit has actually been inspected. Kept out
#: of PRESETS so a production batch does not regenerate it and lose the reference.
QA_REFERENCE: dict[str, Any] = _scene(
    "coastal-moonlight",
    "Coastal Terrace — Moonlight",
    "chill",
    ["water", "coast", "terrace", "night", "moonlight", "calm"],
    (
        "A peaceful Mediterranean coastal terrace at night. A calm dark blue sea extends toward "
        "distant low mountains under a clear moonlit sky with subtle thin clouds and restrained "
        "stars. The immediate foreground is an elegant, simple natural stone terrace. Sparse "
        "vegetation and low architecture at the far left and far right edges only. Cool moonlight "
        "from the upper left with a soft blue ambient fill."
    ),
    {"preset": "cool-moonlight-left", "exposure": 1.0, "keyDirection": [-1, 1, 0.4], "temperatureK": 6500},
    "#071525",
    "The first generated plate, kept for regression comparison.",
)
QA_REFERENCE["version"] = "0.1.0"

#: Everything the CLI can build by name. The reference is reachable, never batch-generated.
ALL_SCENES: dict[str, dict[str, Any]] = {**PRESETS, "coastal-moonlight": QA_REFERENCE}
